### PR TITLE
have extension point for dynamic caching servers in HttpDispatcher

### PR DESCRIPTION
**Pull request by dbu**
inspired by https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/issues/361 i think there are valid use cases where you want a dispatcher that gets server ips from some sort of modifiable source rather than the static configuration file

### CODE REVIEW

**Comment by crevillo** [comment]
i'd say +1 :). 
i can't find another way to solve it from the php side. other option could involve to execute something when those varnish ips changes or a new varnish come in place (talking about autoscaling here), but that will be more a thing for deploy scripts than for this php part.

**Comment by dbu** [comment]
the fancy version would be to inject a server ip provider instead of a simple array. but that feels quite overengineered for the normal use case. with this change, its possible to write your own dispatcher and overwrite getServers to load ips from some runtime information source.

as said in the other issue, the real cloud approach would be message queues with a cache invalidation consumer subscribed to that queue on each caching proxy.

**Comment by plozmun** [comment]
Can you merge this?

**Comment by dbu** [comment]
@ddeboer any objections or is this ok?

**Comment by ddeboer** [comment]
Thanks!

**Comment by plozmun** [comment]
Can you merge this to beta-1? Thank you

**Comment by ddeboer** [comment]
This will be part of 2.0.0-beta2 (or 2.0.0 final).

**Pull request merged**
