### PR TITLE
Set Scrutinizer external coverage timeout

### PR DESCRIPTION
**Pull request by ddeboer**
See https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/216.

### CODE REVIEW

**Comment by dbu** [comment]
:+1:

**Comment by stof** [comment]
My comment on https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/221 would apply here too

**Comment by dbu** [comment]
ups, saw that comment too late. but it seems to work now.

**Comment by ddeboer** [comment]
@stof Not quite, as here we still run code coverage on all builds. We should change that, though.

**Pull request merged**
