### PR TITLE
clarify user context cache impact

### LINKED ISSUE #356: Increasing size of cache for Hash Response in Symfony reverse proxy
There's file which stores cache for Hash Response (`_fos_user_context_hash` request). By default `Vary` is set to `['Cookie', 'Authorization']`. Let's imagine we have 10 anonymous users with different session (Cookie). It will result in 10 entries with the same `X-User-Hash`. The issue is that old (stale) entries are not removed. 

Here is unserialized array from cache for HashResponse (irrelevant data is removed for easier overview):

```
Array
(
    [0] => Array
        (
            [0] => Array
                (
                    [cookie] => Array
                        (
                            [0] => eZSESSID=4id3umajrf71hnn5pp2dufu8j7
                        )
                )
            [1] => Array
                (
                    [x-user-hash] => Array
                        (
                            [0] => 5945886524019aefc21a0e99486455ed340b913f23d342bdc6d7459b1a67eeef
                        )
                    [date] => Array
                        (
                            [0] => Tue, 06 Jun 2017 08:36:40 GMT
                        )
                    [cache-control] => Array
                        (
                            [0] => max-age=30, public
                        )
                )
        )
    [1] => Array
        (
            [0] => Array
                (
                    [cookie] => Array
                        (
                            [0] => eZSESSID=v43eimfa20v9sdgijeb2at4up2
                        )
                )
            [1] => Array
                (
                    [x-user-hash] => Array
                        (
                            [0] => b1731d46b0e7a375a5b024e950fdb8d49dd25af85a5c7dd5116ad2a18cda82cb
                        )
                    [date] => Array
                        (
                            [0] => Tue, 06 Jun 2017 08:36:01 GMT
                        )
                    [cache-control] => Array
                        (
                            [0] => max-age=30, public
                        )
                )
        )
    [2] => Array
        (
            [0] => Array
                (
                    [cookie] => Array
                        (
                            [0] => eZSESSID=nj7ru5lr10pt87jmfvgb1c5qf1
                        )
                )
            [1] => Array
                (
                    [x-user-hash] => Array
                        (
                            [0] => b1731d46b0e7a375a5b024e950fdb8d49dd25af85a5c7dd5116ad2a18cda82cb
                        )
                    [date] => Array
                        (
                            [0] => Tue, 06 Jun 2017 08:27:28 GMT
                        )
                    [cache-control] => Array
                        (
                            [0] => max-age=30, public
                        )
                )
        )
    [3] => Array
        (
            [0] => Array
                (
                    [cookie] => Array
                        (
                            [0] => eZSESSID=rcpnur318ub47rgeevi9mlq2f5
                        )
                )
            [1] => Array
                (
                    [x-user-hash] => Array
                        (
                            [0] => b1731d46b0e7a375a5b024e950fdb8d49dd25af85a5c7dd5116ad2a18cda82cb
                        )
 
                    [date] => Array
                        (
                            [0] => Tue, 06 Jun 2017 08:25:17 GMT
                        )
 
                    [cache-control] => Array
                        (
                            [0] => max-age=30, public
                        )
                )
        )
)
```

First entry is for **logged in** user so there's different `x-user-hash` then in other entries. All other entries are for **anonymous users** coming from different sessions resulting in same `x-user-cache` but as you can see entries `[2]` and `[3]` are stale (according to date and short max-age set to 30 seconds) and **could / should be removed**. 

The result is that this file keeps growing together with number of users: after performing stress tests with ~5000 users file had ~7MB.

Would it be possible to add invalidation for stale cache entries in Hash Response cache?

### PR DESCRIPTION
**Pull request by dbu**
fix #356 

some documentation to at least tell people how it is. unfortunately we can't really fix the issue.

### CODE REVIEW

**Comment by dbu** [comment]
@lolautruche would you be aware of any useful information about the topic of the HttpCache cache folder cleanup? i wonder how far we should go in here - its some pretty long boxes already, i don't want to digress from FOSHttpCache more in this doc :-)

**Comment by lolautruche** [comment]
@dbu Well, the only viable solution for would be to set up a cronjob purging the cache files...

**Comment by Toflar** [comment]
I have some ideas here @dbu. I think I can implement a decent on-a-regular-basis-cleanup-mechanism in the `TaggableStore` implementation 😉

**Comment by Toflar** [comment]
A first version is implemented in https://github.com/FriendsOfSymfony/FOSHttpCache/pull/373.

**Comment by ddeboer** [comment]
@dbu Is this ready to merge?

**Comment by dbu** [comment]
actually yes. can you check if the wording is understandable and merge/ask me for clarifications?

@Toflar did you in the end add something to the taggable store about cleaning up that we should mention in this doc? (guess  we merge as is, and you can then do a separate pull request if there is anything to add)

**Comment by Toflar** [comment]
https://github.com/Toflar/psr6-symfony-http-cache-store#pruning-expired-cache-entries

We just documented how you can configure it. So imho it's all fine here :)

**Comment by dbu** [comment]
cool. i think that pruning does not help when you always add more variants, but then what we say in the doc here is still true.

**Comment by Toflar** [comment]
Yeah, I consider "always adding more variants" as being "heavy proxy work". And the basic statement of "don't use the SF HttpCache if you have heavy proxy work" is still true, even with the auto-pruning store 😄

**Pull request merged**
