### PR TITLE
Fix: UserContextListener set http method wrong

### PR DESCRIPTION
**Pull request by blankse**
Fix: https://github.com/FriendsOfSymfony/FOSHttpCache/issues/377

### CODE REVIEW

**Comment by blankse** [comment]
I add the comment.

**Comment by dbu** [comment]
thanks a lot, merged. i will wait with the release until symfony 3.4 is released, so that we can also merge #376. a patch release is not really possible because the build process with varnish installation had to be changed, and those commits are after BC breaking changes... i hope thats not too much hassle for you? you can use `2.1@dev` until then if thats doable?

**Comment by blankse** [comment]
eZ Platform still using FOSHttpCache 1.4... Can I also create a PR for the 1.4 branch?

**Comment by dbu** [comment]
ups. yeah sure. we should have done it the other way round but the change is so small that there should be no merge conflicts when i later merge 1.4 upstream again. can you do the pull request against the 1.4 branch? there i can also immediately release a patch version with this.

**Comment by blankse** [comment]
Yes, the other way would be better, but I see it too late.

I created the PR against 1.4. Thank you!

**Pull request merged**
