### PR TITLE
document x-cache header for nginx

### PR DESCRIPTION
**Pull request by dbu**
adding doc how to activate the X-Cache header with nginx.

@hpatoio if you happen to know how we could set the X-Cache header only if the backend sends an X-Cache-Debug header, like we do for varnish, then please tell and we can add that.

### CODE REVIEW

**Comment by ddeboer** [comment]
I’m guessing:

```
if ($sent_http_x_cache_debug) {
}
```

Then again, at NGINX they seem to [dislike ifs](http://wiki.nginx.org/IfIsEvil), so perhaps we shouldn't recommend adding one. @hpatoio Wdyt?

**Comment by dbu** [comment]
@hpatoio can you help us here? can i conditionally set the X-Cache header?

**Comment by hpatoio** [comment]
Ciao, just see this. Checking ASAP.

**Comment by hpatoio** [comment]
Is possible using `map`. `X-Cache-Debug` get `HIT` or `MISS` as value. Nothing else right ?  
Going to write the conf.

References:
 - http://nginx.org/en/docs/http/ngx_http_map_module.html 
 - http://serverfault.com/questions/515501/add-expires-header-conditionally-based-on-mime-type-in-nginx

**Comment by dbu** [comment]
it seems that we can know whether we have hit or miss from `$upstream_cache_status`, see https://github.com/FriendsOfSymfony/FOSHttpCache/blob/master/tests/Functional/Fixtures/nginx/fos.conf#L20

i just googled and it seems to me that the header is available as `$sent_http_x_cache_debug`, see  http://wiki.nginx.org/HttpCoreModule#.24sent_http_HEADER

would it not be enough to do 

    if ($sent_http_x_cache_debug) {
        add_header X-Cache $upstream_cache_status;
    }

**Comment by dbu** [comment]
ah, except that nginx can not do an if statement on the header. i suggest we just drop that then, not worth the complication imho.

i have to say i am kind of surprised how awkward nginx is as a proxy. varnish seems a lot more straightforward for this (ok, but then varnish also does nothing else than be a proxy).

**Pull request merged**
